### PR TITLE
Scale bar

### PR DESCRIPTION
**Pull request by DynoAbd786**
Added scale bar, changed video player text to white, bug fixed some file metadata, rest will be fixed by Onaib

### CODE REVIEW

**Comment by onaib-faisal** [comment]
Tested 00T2_P3_0000.ARIS and the metadata table values don't change now. I know that frame 13-14, we should have a change of some of the values in the table. Same issue with the other .ARIS file. I had previously saved frame-by-frame data which might be helpful for you to use to implement this.

**Comment by onaib-faisal** [comment]
Program crashes when I open the folder '3-2-2023 PS with 2000xPSD' while playing the folder 'Streptavidin imaging-12.08.46.399'. Might need to investigate

**Comment by DynoAbd786** [comment]
> Tested 00T2_P3_0000.ARIS and the metadata table values don't change now. I know that frame 13-14, we should have a change of some of the values in the table. Same issue with the other .ARIS file. I had previously saved frame-by-frame data which might be helpful for you to use to implement this.

Noted. will fix

**Comment by DynoAbd786** [comment]
> Program crashes when I open the folder '3-2-2023 PS with 2000xPSD' while playing the folder 'Streptavidin imaging-12.08.46.399'. Might need to investigate

removed calls to reset data when loading a new file or folder in.

**Review by onaib-faisal — APPROVED** [review]
Bugs fixed. Looks good to go!

**Pull request merged**
